version: 2
updates:
  # Mantener las dependencias de Python actualizadas
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"

  # Mantener las GitHub Actions actualizadas
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
